### ISSUE TITLE
Cross-platform incompatibility

### ISSUE THREAD

**Issue by derickboss1** [okpy/ok#1371]
If I run `python3 ok -q [assignment]` on one OS, and then tried to run it again via a different OS, I get the error `dbm.error: db type could not be determined`. Tested by initially running on Windows 10, then running it on linux

The entire error message is:
```
Checking for software updates...
OK is up to date
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok/__main__.py", line 46, in <module>
  File "ok/client/cli/ok.py", line 209, in main
  File "ok/client/protocols/grading.py", line 46, in run
  File "ok/client/protocols/grading.py", line 66, in grade
  File "ok/client/utils/storage.py", line 40, in store
  File "/usr/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.7/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```

**Comment by mehrdadn** [comment]
What does `python3 -c "import sys; print(sys.version)"` show on each platform?

**Comment by mehrdadn** [comment]
Hmm, interesting. I'm not getting an error, but in my case (64-bit Windows vs. Arch WSL) they don't recognize each others' logins, and so ask me to log in again. Still, that shouldn't be happening either...

**Comment by derickboss1** [comment]
If I use linux first to run OK, then try to run OK in windows, I get a slightly different error message:
```
Checking for software updates...
OK is up to date
Traceback (most recent call last):
  File "C:\Users\deric\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\deric\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok\__main__.py", line 46, in <module>
  File "ok\client\cli\ok.py", line 209, in main
  File "ok\client\protocols\grading.py", line 46, in run
  File "ok\client\protocols\grading.py", line 66, in grade
  File "ok\client\utils\storage.py", line 40, in store
  File "C:\Users\deric\AppData\Local\Programs\Python\Python37-32\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "C:\Users\deric\AppData\Local\Programs\Python\Python37-32\lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "C:\Users\deric\AppData\Local\Programs\Python\Python37-32\lib\dbm\__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
```

**Comment by mehrdadn** [comment]
Yeah, it seems to repro like this:

	> wsl python3 -c "import dbm; dbm.open('Temp.dbm', 'c')[b'1'] = b'2'"
	
	>     python3 -c "import dbm; dbm.open('Temp.dbm', 'c')[b'1'] = b'2'"
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "...\lib\dbm\__init__.py", line 91, in open
	    "available".format(result))
	dbm.error: db type is dbm.gnu, but the module is not available

**Comment by derickboss1** [comment]
Is there going to be a fix for it, or do I need to file an issue on https://github.com/okpy/ok-client instead?

**Comment by evelynluw** [comment]
Same issue for me. A quick fix is to delete the __pycache__ folder and all files starting with .ok to reinitialize ok grader
