### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by StephenZhiyiLin** [okpy/ok#1422]
I am studying UCB's CS61A course. I have downloaded the ok program from [the course website](https://inst.eecs.berkeley.edu/~cs61a/fa20/lab/lab00/). However, when I was trying to run the ok program on my terminal, there was something wrong and the terminal reported ModuleNotFoundError: No module named 'urllib3.packages.six.moves'. How can I solve this problem?

The error tracebacks are:
```
$ python ok -q python-basics -u --local
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Root_Server\Software_Engineering\Courses\CS61A\Lab\lab00\ok\__main__.py", line 14, in <module>
  File "D:\Root_Server\Software_Engineering\Courses\CS61A\Lab\lab00\ok\client\cli\ok.py", line 48, in <module>
  File "D:\Root_Server\Software_Engineering\Courses\CS61A\Lab\lab00\ok\client\api\assignment.py", line 5, in <module>
  File "D:\Root_Server\Software_Engineering\Courses\CS61A\Lab\lab00\ok\requests\__init__.py", line 43, in <module>
  File "D:\Root_Server\Software_Engineering\Courses\CS61A\Lab\lab00\ok\urllib3\__init__.py", line 7, in <module>
  File "D:\Root_Server\Software_Engineering\Courses\CS61A\Lab\lab00\ok\urllib3\connectionpool.py", line 11, in <module>
  File "D:\Root_Server\Software_Engineering\Courses\CS61A\Lab\lab00\ok\urllib3\exceptions.py", line 2, in <module>
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

I have reinstalled the urllib3 package, but I still can not solve the problem. I hope that I can run the ok program on my terminal normally in order to test my labs, assignments and homeworks. I would be appreciated if I can get your help!

PS:
1. My OS is Windows and my terminal is Git-bash.
2. I have tried to run the ok program on the terminal of Linux, but the terminal also reported ModuleNotFoundError: No module named 'urllib3.packages.six.moves'.

**Comment by beeburt** [comment]
Same issue, is there a fix for this?

**Comment by StephenZhiyiLin** [comment]
No,  I failed to solve this problem.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by beeburt** [comment]
I used python version 3.11 (I first tried version 3.10 and it worked) in a virtual environment. 

ok doesn't like pyhon3.12 for some reason.

I'm on Fedora, so first I installed Python3.11 with:

    sudo dnf install python 3.11

then in my directory for the course (venv would work too):

    virtualenv --python=$(which python3.11) cs61a-venv

then activate it:

    source cs61a-venv/bin/activate

**Comment by NikoHYK** [comment]
我也遇到这样的问题，刚刚成功解决。
我是学的2023 Fall的课程，使用python3.12和3.11都显示报错，后来去课程页面看了「[Lab 00: Getting Started](https://inst.eecs.berkeley.edu/~cs61a/fa23/lab/lab00/)」，里面推荐使用

> Python 3.7 or later (ideally Python 3.9)

于是我卸载了3.12和3.11，安装了3.9，就可以运行了。

**Comment by paracosmgracee** [comment]
> 我也遇到这样的问题，刚刚成功解决。 我是学的2023 Fall的课程，使用python3.12和3.11都显示报错，后来去课程页面看了「[Lab 00: Getting Started](https://inst.eecs.berkeley.edu/~cs61a/fa23/lab/lab00/)」，里面写着
> 
> > Python 3.7 or later (ideally Python 3.9)
> 
> 我感觉可能是版本太高的问题，于是我卸载了3.12和3.11，安装了3.9，就可以运行了。

感谢老哥，就是版本问题，解决了！

**Comment by xukristenyan** [comment]
I'm learning the Fall 2020 version and encountered the same issue. The python version I'm using is 3.9 in a conda environment. The way I solved it is: instead of running "**python3** ok blahblah", using "**python** ok blahblah". It works for me. Just post here in case other people got the same error.
